name: morekast
description: Multiroom Audio Portable
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wifi_iot: ^0.3.0
  flutter_riverpod: ^2.5.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  network_tools: ^5.0.0
  just_audio: ^0.9.36
  audio_service: ^0.18.1
  http: ^1.2.1
  web_socket_channel: ^3.0.0
  flutter_nearby_connections: ^1.0.0

flutter:
  uses-material-design: true